### ISSUE TITLE
Request for delete MacOS as SO enviroment for testing

### ISSUE THREAD

**Issue by fransdns** [Narrify/narrify-back-end#10]
Chicos, creo que debemos de quitar las pruebas en MacOS, nuestro codigo solo correría en servidores Linux o Windows.
Probar en MacOS hace que los tests tomen más tiempo innecesariamente.

**Comment by fransdns** [comment]
<img width="430" alt="image" src="https://github.com/user-attachments/assets/c6045331-ec2a-4fd5-a61f-9c4676417b6a">

**Comment by JustMaykol** [comment]
Done!
